### ISSUE TITLE
Issues #1

### ISSUE THREAD

**Issue by MedAlexey** [MedAlexey/Minesweeper#1]
@gagarski прошу проверить

**Comment by gagarski** [comment]
Нашёл следующие баги:
1. Если выиграть игру, а потом, не нажимая "OK", кликнуть по мине, появится второй диалог с надписью "Вы проиграли". В связи с этим, советую посмотреть на [стандартные способы создания модальных диалогов в Swing](https://docs.oracle.com/javase/tutorial/uiswing/components/dialog.html) вместо реализации  на основе `JFrame`
2. Если задать слишком большое поле, то оно не влезает в окно. Следует решить эту проблему (прокрутка, разумное ограничение размера поля + ограничение размера окна снизу, разумное масштабирование, либо какая-то комбинация из этих способов).
3. При большом размере поля (100х100, 5 мин) ваш поиск открытых соседей валится со `StackOverflowError`. Лучше переделать этот поиск с использованием явного стека или очереди вместо рекурсии.

По коду:
0. Нужно добавить тесты для того кода, который можно протестировать без взаимодействия с пользователем: подсчёт числа мин, открытие соседних клеток и т. д.
1. Классы `Line` и `Point`, похоже, не используются.
2. У класса `Cell` все поля package-private и вы напрямую их изменяете. Постарайтесь сделать поля приватными и выделить нужный API этого класса.
3. `minesBeside` и `color` у `Cell` могут быть вычисляемыми полями (исходя из других полей). Это позволит избавиться от логики изменения этох полей в `PlayingField`. По поводу первого, следует поэкспериментировать, возможно это сильно ухудшит производительность, второе одноздачно следует сделать так, заодно избавитесь от повторяющихся констант в коде.
4. Магическим числам (цвета, размеры и т. п) следует дать осмысленные имена и вынести в статические константы.
5. У вас местами встречается код, который выполняет некоторые одинаковые действия для всех соседей ячейки (то есть 6 подряд одинаковых кусков кода). Предлагаю сделать у ячейки метод, вовзращающий соседей в таком виде, чтобы можно было по ним итерироваться (список или `Stream`).

**Comment by gagarski** [comment]
0. Всё ещё нет тестов
1. Поле всё ещё может не влезать в окно (даже с размером по умолчанию)
2. В классе `Settings` есть глобальные изменяемые поля. Это плохой стиль (практически, глобальные переменные). Советую отделить логику отображения окна с настройками с самими настройками (классы `SettingsFrame` и `Settings`). Лучше сделать так, чтобы после взаимодействия с окном настроей создавался объект класса `Settings` и передавался в игру.
3. В коде всё ещё присутствуют "магические" константы
4. `openBrothers()` вы переделали правильно, но способ передачи туда начальной клетки (через поле класса) не самый удачный. Лучше передавать начальную клетку (или очередь с ней) с помощью аргумента.
5. Необязательно явно хранить значения, которые возвращают методы класса. Цвет, например, можно вычислять прямо в геттере и не хранить в поле. То же самое и с минами вокруг (но как я уже написал ранее, можно столкнуться с проблемами производительности, нужно экспериментировать)
6. Местами есть косяки с Java Code Style. Например, методы следует называть с маленькой буквы: (`Button1Pressed` -> `button1Pressed`), константы - большими буквами через подчёркивания (`imgHeight` -> `IMG_HEIGHT`). Следование принятым конвенциям сильно улучшает читаемость кода. Изучите [этот документ](http://www.oracle.com/technetwork/java/codeconventions-150003.pdf), он не такой большой.

**Comment by gagarski** [comment]
По прокрутке: вместо переопределения `getSize()` нужно переопределить `getPreferredSize()` (переопределение метода `getSize()` следует убрать). После этого прокрутка заработала почти правильно (правда, вы немного ошиблись с размером в ширину).

Класс `Settings` вы сделали, но сами сеттинги всё равно достаёте из статических переменных. Я предлагал сохранять объект `Settings` во фрейме после клика на ОК, а затем доставать этот объект из SettingsFrame и передавать его в игровое поле. 

Константы типа `IMAGE_DISPLACEMENT`, напротив, лучше объявить статическими, поскольку они неизменяемы и общие для любого объекта класса.

Случайно обнаружил ещё один небольшой баг: клетку, на которой установлен флаг не следует открывать в `openBrothers` (должно быть легко исправить).

Если вы хотите получить отличную итоговую оценку, то хотелось, чтобы вы исправили эти замечания.
